# Generated by Django 3.2.3 on 2021-07-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('calories', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('carbs', models.CharField(max_length=20)),
                ('fat', models.CharField(max_length=20)),
                ('instructions', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
