# Generated by Django 3.2.3 on 2021-07-09 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bigshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipe',
            name='users',
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='auth.user'),
            preserve_default=False,
        ),
    ]
